#ifndef _ASSEMBLE_ERRS_H_
#define _ASSEMBLE_ERRS_H_

typedef enum _ASSEMBLE_ERROR {
  ADDR_RESOLUTION_FAIL = 1<<3,
  SYNTAX_PARSE_FAIL = 1<<4,
  ALLOC_FAIL = 1<<5
} ASSEMBLE_ERROR;

typedef enum _SYNTAX_ERROR {
  START_DIRECTIVE_WRONG_PLACE = 1,
  PROGRAM_NAME_TOO_LONG,
  LOC_EXCEEDED,
  INVALID_OPERAND_FORMAT,
  INVALID_SYMBOL_NAME,
  OPERAND_MISSING,
  DUPLICATE_SYMBOL,
  UNDEFINED_OPCODE,
  UNDEFINED_SYMBOL,
  CONSTANT_TOO_LARGE,
  TOKEN_MISSING,
  UNDEFINED_REGISTER
} SYNTAX_ERROR;

extern char const *SYNTAX_ERROR_MESSAGES[];

#endif